### PR TITLE
sync

### PR DESCRIPTION
**Pull request by ocefpaf**
This recipe is quite different from the one here and maybe we should put this in a branch and slowly transition to it? (Or maybe just rip the band-aid and get a new and shiny recipe :wink:)

@jjhelmus looks like you are the one that wrote this version, do you mind taking a look?

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by mariusvniekerk** [comment]
So we might not have to wait on the new compilers, but we can't import tensorflow in the very old centos image we use.

**Comment by ocefpaf** [comment]
> So we might not have to wait on the new compilers, but we can't import tensorflow in the very old centos image we use.

I realized that after I send the comment. @jjhelmus and @msarahan told me that already a few times and I always forget.

**Comment by jjhelmus** [comment]
I bit of background on what this recipe is doing.  This produced three Keras related packages: `keras-base` contains the actual Python code and does not require a backend, `keras` adds a requirement on keras and `keras-gpu` add a requirements on tensorflow-gpu.  The idea here is that most users will want to install `keras` and have a working environment with the Tensorflow backend.  If you have a GPU you can install keras-gpu.  More advanced users can install `keras-base` and then install a backend on their own, perhaps PyTorch.

I think the import tests will need to be skipped on linux and os-x.  The tensorflow conda packages repackaging the wheels from PyPI which require newer versions of on Linux and macOS that used on the CI services.

**Comment by jjhelmus** [comment]
Should the activation scripts be removed as well?  They are not used in the recipe.

**Comment by ocefpaf** [comment]
> Should the activation scripts be removed as well? They are not used in the recipe.

Missed those! Just updated and rebased.

**Pull request closed without merging**
