### PR TITLE
fix keras-* requirements

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
[Requirements in the `setup.py` file](https://github.com/keras-team/keras/blob/2.2.4/setup.py#L35-L41):

numpy>=1.9.1
scipy>=0.14
six>=1.9.0
pyyaml
h5py
keras_applications>=1.0.6
keras_preprocessing>=1.0.5

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by kyleabeauchamp** [comment]
What's the status of this PR?  I think it might unblock https://github.com/conda-forge/tensorflow-feedstock/pull/66 due to numpy pinning stuff.

**Comment by dhirschfeld** [comment]
@conda-forge-admin please rerender

**Comment by dhirschfeld** [comment]
Looks like it's failing on py37 but the error message doesn't appear to make much sense to me:
```
TEST START: C:\bld\win-64\keras-2.2.4-py37_1.tar.bz2
Adding in variants from C:\Users\appveyor\AppData\Local\Temp\1\tmpoh1k8b4m\info\recipe\conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from C:\Users\appveyor\AppData\Local\Temp\1\tmpoh1k8b4m\info\recipe\conda_build_config.yaml
Renaming work directory,  C:\bld\keras_1551223013718\work  to  C:\bld\keras_1551223013718\work_moved_keras-2.2.4-py37_1_win-64
Collecting package metadata: ...working... done
Solving environment: ...working... failed
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform win-64: {'keras==2.2.4=py37_1'}
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform win-64: {'keras==2.2.4=py37_1'}
Tests failed for keras-2.2.4-py37_1.tar.bz2 - moving package to C:\bld\broken
WARNING:conda_build.build:Tests failed for keras-2.2.4-py37_1.tar.bz2 - moving package to C:\bld\broken
TESTS FAILED: keras-2.2.4-py37_1.tar.bz2
```

**Comment by mariusvniekerk** [comment]
That generally means some dependency is missing for py37

**Comment by kyleabeauchamp** [comment]
I definitely saw some strange keras-numpy-TF pinning / requirement issues over in https://github.com/conda-forge/tensorflow-feedstock/pull/66; I only saw issues on windows, though, so I skipped windows on that PR to get things green.

**Comment by dhirschfeld** [comment]
Yeah, I figured but AFAICS the error message only lists the package itself rather than the missing dependency which isn't very helpful :(

**Comment by jjhelmus** [comment]
closing in favor of #37

**Pull request closed without merging**
