### PR TITLE
Update recipe to version 1.1.1

### PR DESCRIPTION
**Pull request by ghego**

### CODE REVIEW

**Comment by jakirkham** [comment]
Restarted CIs.

cc @ericdill

**Comment by jakirkham** [comment]
Still getting GLIBC issues. @ericdill do you know how this was able to work before?

**Comment by ericdill** [comment]
@jakirkham @ghego  I've tracked this down to something that happened between the 1.0.8 and 1.1.0 tags on keras.  Here's the full diff: https://github.com/fchollet/keras/compare/1.0.8...1.1.0

It's going to be a while before I have some cycles to dig in to this further as things are on fire at my day job.

**Comment by ericdill** [comment]
Welp, good news bad news.  

good news: I found the commit that causes this glibc issue. It's this one: https://github.com/fchollet/keras/commit/8af0264a77539a12e05a65ff1f1f43af1094c493

bad news: All this commit does is set tensorflow as the default back end.  As such, I am not convinced that the keras + tensorflow conda packages *ever* worked.  I am checking different versions of tensorflow with the "broken" commit to see if any of them don't have this glibc issue

**Comment by jakirkham** [comment]
Good find @ericdill (even if it isn't what we want to hear 😜).

Maybe we can override the backend for the tests during our build. Not ideal, but as noted `tensorflow` doesn't support our GLIBC version. So not sure what other easy things we can try.

**Comment by ericdill** [comment]
These are the tensorflow packages I have tried:

```
$ conda search tensorflow
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
tensorflow                   0.7.1                    py27_0  conda-forge/linux-64 
                             0.7.1                    py34_0  conda-forge/linux-64 
                             0.8.0                    py27_0  conda-forge/linux-64 
                             0.8.0                    py34_0  conda-forge/linux-64 
                             0.9.0                    py27_0  conda-forge/linux-64 
                             0.9.0                    py34_0  conda-forge/linux-64 
                             0.9.0                    py35_0  conda-forge/linux-64 
                             0.10.0rc0           np111py27_0  defaults        
                             0.10.0rc0           np111py34_0  defaults        
                             0.10.0rc0           np111py35_0  defaults        
                             0.10.0                   py27_0  conda-forge/linux-64 
                             0.10.0                   py34_0  conda-forge/linux-64 
                             0.10.0                   py35_0  conda-forge/linux-64 
                             0.11.0rc0                py27_0  conda-forge/linux-64 
                             0.11.0rc0                py34_0  conda-forge/linux-64 
                             0.11.0rc0                py35_0  conda-forge/linux-64 
                             0.11.0rc2                py27_0  conda-forge/linux-64 
                             0.11.0rc2                py34_0  conda-forge/linux-64 
                             0.11.0rc2                py35_0  conda-forge/linux-64 
                             0.11.0                   py27_0  conda-forge/linux-64 
                             0.11.0                   py34_0  conda-forge/linux-64 
                             0.11.0                   py35_0  conda-forge/linux-64 
```

The **only** one that doesn't have this GLIBC issue is the one from defaults (0.10.0rc2).

**Comment by ericdill** [comment]
> Maybe we can override the backend for the tests during our build. Not ideal, but as noted tensorflow doesn't support our GLIBC version. So not sure what other easy things we can try.

Looks like keras supports environmental variable flags to tweak the backend: https://keras.io/backend/

Removing the test imports and adding this as a test/commands line would probably work: 
```
KERAS_BACKEND=theano python -c "from keras import backend"
```

Ok this is really the last thing i'll be able to do for a while.  Good luck!

**Comment by jakirkham** [comment]
Awesome thanks again Eric!

**Comment by jakirkham** [comment]
So I think the simplest way to move this forward @ghego is to add a [`run_test.py`]( https://github.com/conda-forge/scipy-feedstock/blob/0b9933f00cac17d705dae805e4e5b2e2a9fb22bb/recipe/run_test.py ) file like this linked one in `scipy` and change the [`os.environ` line]( https://github.com/conda-forge/scipy-feedstock/blob/0b9933f00cac17d705dae805e4e5b2e2a9fb22bb/recipe/run_test.py#L6 ) to set the backend. This should let us test against a backend we can support and test against like `theano`.

Please let me know if you have any questions.

**Comment by jakirkham** [comment]
Also we need a [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.6.1`.

**Comment by ghego** [comment]
Yeah, I suspected that the switch to default Tensorflow backend was the issue. Great find @ericdill. @jakirkham why wouldn't setting a variable in `meta.yaml` suffice?

http://conda.pydata.org/docs/building/environment-vars.html?highlight=pkg_version#environment-variables-set-during-the-build-process

**Comment by ghego** [comment]
apparently they know the issue in the tensorflow-feedstock https://github.com/conda-forge/tensorflow-feedstock/blob/master/recipe/meta.yaml#L34

**Comment by jakirkham** [comment]
> why wouldn't setting a variable in `meta.yaml` suffice?

There is no way to set environment variables in `meta.yaml`. There is a way to allow environment variables set externally into the build process, but that doesn't help us solve this problem.

**Comment by ghego** [comment]
got it. Does it mean I also have to replace the test section in meta.yaml with something along the line of the scipy example you shared?

**Comment by croth1** [comment]
What is the status here, can this be merged?

**Comment by ghego** [comment]
This is clearly outdated since Keras is now at 1.2.0. I'll update it again this week.

**Pull request closed without merging**
