### PR TITLE
fix requirements

### PR DESCRIPTION
**Pull request by jjhelmus**
Adjust requirements to match those found in the wheel

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
CI failures are because `tensorflow` is not available for Python 3.7 on linux and osx until 1.13.1 which has not yet been packaged.

**Comment by ocefpaf** [comment]
> CI failures are because `tensorflow` is not available for Python 3.7 on linux and osx until 1.13.1 which has not yet been packaged.

Do you want to merge this to fix 2.7 and 3.6 or do you want to wait for tensorflow?

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Awesome! Thanks @jjhelmus!

**Pull request merged**
