### PR TITLE
Use POSIX compliant string equality operator

### PR DESCRIPTION
**Pull request by marjinal1st**
In some systems, Keras activation script fails due to string equality check. I refactored to check it via single equality sign, a.k.a. standard for POSIX compliant shells.

Example:

image

Info:

https://unix.stackexchange.com/a/208097
https://stackoverflow.com/a/1089833

### CODE REVIEW

**Comment by croth1** [comment]
Doesn't that trigger a new issue with zsh, similar to this one? 
https://github.com/conda-forge/openjdk-feedstock/issues/22

**Comment by marjinal1st** [comment]
I'm currently using zsh and double equals sign throws an error. If you like, I can change the script to double square brackets instead of single equals.

BTW I have no idea why AppVeyor build failed.

**Comment by croth1** [comment]
you can try to rerender - maybe that already solves the appveyor issue:
https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender

**Comment by marjinal1st** [comment]
@conda-forge-admin, please rerender

**Comment by marjinal1st** [comment]
Any idea about why Travis CI didn't start yet? I manually triggered a build from my branch and [it's completed](https://travis-ci.org/marjinal1st/keras-feedstock).

**Comment by marjinal1st** [comment]
@conda-forge-admin, please rerender

**Comment by croth1** [comment]
> Any idea about why Travis CI didn't start yet? I manually triggered a build from my branch and it's completed.

ping @conda-forge/core

**Comment by isuruf** [comment]
conda-forge's travis-ci queue is really really long. Might have to wait a few more days or merge this now if it works in your fork.

**Comment by marjinal1st** [comment]
@conda-forge-admin, please rerender

**Comment by mariusvniekerk** [comment]
i bumped the build number here to get the new activation script to be shipped.  Will merge once tests pass

**Pull request merged**
