### PR TITLE
Update to Keras v2.1.1

### PR DESCRIPTION
**Pull request by CellDynamics**

### CODE REVIEW

**Comment by croth1** [comment]
` - tensorflow <=1.0.1  # [osx]` is this still ok? I remember including this quite  some time ago due to a problem with how we built tensorflow. Does keras work with the old version?

**Comment by guptarajat** [comment]
Any plan to merge this?

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by mariusvniekerk** [comment]
closing outdated

**Pull request closed without merging**
