### PR TITLE
Update to 1.1.0 and rerender the feedstock

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by jakirkham** [comment]
This is strange. It looks like you may not have forked based on the CIs, but the PR clearly says this is coming from your fork. 😕

**Comment by ericdill** [comment]
Well I did accidentally push to github.com/conda-forge/keras-feedstock because my upstream branch was not set correctly...

I cancelled the builds on the CI services that my accidental-push-to-origin created and set my upstreams correctly, then re-pushed to my branch on ericdill/keras-feedstock

**Comment by Ninad998** [comment]
Hi, guys any updates on this?

**Comment by ericdill** [comment]
@Ninad998 there's an issue with the tensorflow conda package that is going to be painful to resolve. Not sure we can package 1.1.0 until https://github.com/conda-forge/tensorflow-feedstock/issues/19 is resolved

**Comment by Ninad998** [comment]
@ericdill no worries 👍

**Comment by jakirkham** [comment]
The new tensorflow is out. Going to need to re-render again to get this working. Will try giving CircleCI a restart though as that CI should be ok.

**Comment by babhishek21** [comment]
Keras 1.2.0 is out. I suggest, that if you are going to re-render this feedstock, you do it with ver. 1.2.0.

**Comment by babhishek21** [comment]
The `tensorflow` feedstock was updated to `ver 0.12.1` in this [PR](https://github.com/conda-forge/tensorflow-feedstock/issues/25).  The `protobuf` feedstock was updated to `ver 0.3.1` (with no support for python 2.X on Windows; see [here](https://github.com/conda-forge/protobuf-feedstock/issues/17)). Perhaps we should try rebuilding again?

**Comment by mariusvniekerk** [comment]
Closing in favor of #6

**Pull request closed without merging**
